global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
    - "./rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend'
    static_configs:
      - targets: ['nginx:80']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']

  - job_name: 'nginx'
    static_configs:
      - targets : ['nginx-exporter:9113']