# Configuration globale
global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@example.com'

# Modèles d'alerte
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Routes des alertes
route:
  group_by: ['alertname']           # Grouper par nom d'alerte
  group_wait: 10s                   # Attendre 10s avant d'envoyer un groupe
  group_interval: 10s               # Intervalle entre les groupes
  repeat_interval: 1h               # Répéter toutes les heures
  receiver: 'web.hook'              # Récepteur par défaut
  
  # Routes spécifiques
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
    - match:
        severity: warning  
      receiver: 'warning-alerts'

# Récepteurs d'alerte
receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'https://webhook.site/e6176ab2-f49a-4716-8faf-264feeab8056/'
        
  - name: 'critical-alerts'
    webhook_configs:
      - url: 'https://webhook.site/e6176ab2-f49a-4716-8faf-264feeab8056/critical'
        send_resolved: true
        
  - name: 'warning-alerts'
    webhook_configs:
      - url: 'https://webhook.site/e6176ab2-f49a-4716-8faf-264feeab8056/warning'
        send_resolved: true

# Suppressions d'alerte
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']