name: Deploy to Development Machine

on:
  push:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Pull latest changes
        run: git pull origin ${{ github.ref_name }}
        working-directory: .

      # === TODOS Cleanup ===
      - name: Stop and clean todos
        run: |
          docker-compose down -v --remove-orphans
          docker rm -f todos_backend todos_frontend todos_db
          docker network prune -f
          docker image prune -f
        working-directory: ./todos
        continue-on-error: true

      # === PROM-GRAPH Cleanup ===
      - name: Stop and clean prom-graph
        run: |
          docker-compose down -v --remove-orphans
        working-directory: ./prom-graph
        continue-on-error: true

      - name: Create monitoring network
        run : |
          docker network create monitoring network 

      # === TODOS Build and Deploy ===
      - name: Build and deploy todos
        run: |
          docker-compose build --no-cache
          docker-compose up -d
          echo "Waiting for todos services..."
          Start-Sleep -Seconds 20
          docker-compose ps
        working-directory: ./todos

      # === PROM-GRAPH Build and Deploy ===
      - name: Build and deploy prom-graph
        run: |
          docker-compose build --no-cache
          docker-compose up -d
          echo "Waiting for Prometheus stack..."
          Start-Sleep -Seconds 15
          docker-compose ps
        working-directory: ./prom-graph

      # === Health Check ===
      - name: Verify backend health
        run: |
          $maxAttempts = 12
          $attempt = 0
          while ($attempt -lt $maxAttempts) {
            try {
              $res = Invoke-WebRequest -Uri http://localhost:8080/api/health -UseBasicParsing
              if ($res.StatusCode -eq 200) {
                Write-Host "✅ Backend is healthy through Nginx!"
                exit 0
              } else {
                Write-Warning "⚠️ Status: $($res.StatusCode). Waiting..."
              }
            } catch {
              Write-Host "⏳ Attempt $($attempt+1)/$maxAttempts failed. Retrying in 5s..."
            }
            Start-Sleep -Seconds 5
            $attempt++
          }
          Write-Error "❌ Backend (via Nginx) did not respond after $maxAttempts attempts."
          exit 1

      # === Show logs on failure ===
      - name: Show logs on failure
        if: failure()
        run: |
          echo "=== Backend logs ==="
          docker-compose logs backend
          echo "=== Frontend logs ==="
          docker-compose logs frontend
          echo "=== Database logs ==="
          docker-compose logs db
        working-directory: ./todos
