name: Deploy to Development Machine

on:
  push:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Pull latest changes
        run: |
          git pull origin ${{ github.ref_name }}
        working-directory: .

      - name: Stop and clean todos
        run: |
          docker-compose down -v --remove-orphans || true
          docker rm -f todos_backend todos_frontend todos_db || true
          docker network prune -f || true
          docker image prune -f || true
        working-directory: ./todos

      - name: Stop and clean prom-graph
        run: |
          docker-compose down -v --remove-orphans || true
        working-directory: ./prom-graph

      - name: Build and deploy todos
        run: |
          docker-compose build --no-cache
          docker-compose up -d
          echo "Waiting for todos services..."
          sleep 20
          docker-compose ps
        working-directory: ./todos

      - name: Build and deploy prom-graph
        run: |
          docker-compose build --no-cache
          docker-compose up -d
          echo "Waiting for Prometheus stack..."
          sleep 15
          docker-compose ps
        working-directory: ./prom-graph

      - name: Verify backend health
        run: |
          curl -f http://localhost:8000/api/health || exit 1
          echo "Backend is healthy!"

      - name: Show logs on failure
        if: failure()
        run: |
          echo "=== Backend logs ==="
          docker-compose logs backend || true
          echo "=== Frontend logs ==="
          docker-compose logs frontend || true
          echo "=== Database logs ==="
          docker-compose logs db || true
        working-directory: ./todos
